### ISSUE TITLE
empty token.json file created

### ISSUE THREAD

**Issue by SmartLayer** [luisbustalu/Google-Spaces-Tasks-reporter#4]
````
$ python3 scrapper.py 
Please visit this URL to authorize this application: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=455140852287-mm9ifa0vmfkbchrhrl56ci5lidj9q5c4.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A7276%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fchat.spaces+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fchat.messages+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fchat.messages.readonly&state=spAe7CXqhwx73MCc3eUtoJoPgOwfWk&access_type=offline
2024-07-16 09:59:22,955 - INFO - "GET /?state=spAe7CXqhwx73MCc3eUtoJoPgOwfWk&code=4/0AcvDMrCtaOse9TE2YuWCPsZN7ZpH8zX5ecfsBUgPmOxiGAexzAHytxiY5DoS72gRhePHyw&scope=https://www.googleapis.com/auth/chat.spaces%20https://www.googleapis.com/auth/chat.messages%20https://www.googleapis.com/auth/chat.messages.readonly HTTP/1.1" 200 65
Traceback (most recent call last):
  File "/home/weiwu/code/Google-Spaces-Tasks-reporter/scrapper.py", line 170, in <module>
    main()
  File "/home/weiwu/code/Google-Spaces-Tasks-reporter/scrapper.py", line 141, in main
    creds = get_credentials()
            ^^^^^^^^^^^^^^^^^
  File "/home/weiwu/code/Google-Spaces-Tasks-reporter/scrapper.py", line 40, in get_credentials
    token.write(creds.to_json())
                ^^^^^^^^^^^^^
AttributeError: 'Credentials' object has no attribute 'to_json'
````
I guess the file token.json is broken:
````
$ ls -l token.json
-rw-rw-r-- 1 weiwu weiwu 0 Jul 16 09:59 token.json
````

**Comment by overseers-desk** [comment]
turns out to be caused by dated libraries.
